package com.bahlam.training.rules;

import com.bahlam.brms.training.model.Order;
import com.bahlam.brms.training.model.Customer;
import com.bahlam.brms.training.model.Discount;

rule "Gold Customers - 20% Discount"
    when
        
        $o: Order( $customer: customer, discount == null )
        $c: Customer( category == Category.GOLD, this == $customer )
    then
        System.out.println("Executing Gold Customer 20% Discount Rule!");
        $o.setDiscount(new Discount(20.0));
        update($o);
end
