package com.bahlam.brms.training.rules;

import com.bahlam.brms.training.model.Customer;
import com.bahlam.brms.training.model.Order;
import com.bahlam.brms.training.model.Discount;


rule "Bronze Customers - 5% Discount"
    when
        $o: Order( $customer: customer, discount == null )
        $c: Customer( category == Category.BRONZE, this == $customer )
    then
    	System.out.println("Executing Bronze Customer 5% Discount Rule!");
        $o.setDiscount(new Discount(5.0));
        update($o);
end